version: 2.1
orbs:
  android: circleci/android@2.5.0
jobs:
  build:
    executor:
      name: android/android-machine
      resource-class: large
      tag: default
    steps:
      - checkout
      - run: java --version
      - restore_cache:
          key: android-orb-v1-
      - android/change-java-version:
          java-version: 17
          
      # Konfigurasi memory dan AAPT
      - run:
          name: Configure Build Settings
          command: |
            mkdir -p ~/.gradle
            echo "org.gradle.jvmargs=-Xmx6g -XX:+HeapDumpOnOutOfMemoryError" >> ~/.gradle/gradle.properties
            echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
            echo "org.gradle.parallel=true" >> ~/.gradle/gradle.properties
            echo "android.enableAapt2=true" >> ~/.gradle/gradle.properties
            echo "android.aapt2FromMavenOverride=com.android.tools.build:aapt2:7.3.0-8691043" >> ~/.gradle/gradle.properties
      
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
          
      - run:
          name: Clean Project
          command: ./gradlew clean
          
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
          
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
            - ~/.gradle
            
      # Build dengan parameter AAPT
      - run:
          name: Build Release
          command: |
            ./gradlew assembleRelease \
            -x lint \
            --stacktrace \
            -Pandroid.aapt2FromMavenOverride=com.android.tools.build:aapt2:7.3.0-8691043 \
            -Pandroid.enableAapt2=true
          
      - store_artifacts:
          path: app/build/reports
          destination: reports
          
      - store_artifacts:
          path: app/build/outputs/apk/release/
          destination: release-apk

workflows:
  version: 2
  build_and_test:
    jobs:
      - build