version: 2.1
orbs:
  android: circleci/android@2.5.0
jobs:
  build:
    executor:
      name: android/android-machine
      resource-class: large
      tag: default
    steps:
      - checkout
      - run: java --version
      - restore_cache:
          key: android-orb-v1-
      - android/change-java-version:
          java-version: 17
      # Tambahkan konfigurasi memory
      - run:
          name: Configure Gradle Memory
          command: |
            mkdir -p ~/.gradle
            echo "org.gradle.jvmargs=-Xmx6g -XX:+HeapDumpOnOutOfMemoryError" >> ~/.gradle/gradle.properties
            echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
            echo "org.gradle.parallel=true" >> ~/.gradle/gradle.properties
      
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
          
      # Tambahkan baseline untuk lint
      - run:
          name: Create Lint Baseline
          command: ./gradlew :core:updateLintBaseline :app:updateLintBaseline :favorite:updateLintBaseline
          
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
          
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
            - ~/.gradle
            
      # Pisahkan build per modul
      - run:
          name: Build Core Module
          command: ./gradlew :core:assembleRelease --stacktrace
          
      - run:
          name: Build App Module
          command: ./gradlew :app:assembleRelease --stacktrace
          
      - run:
          name: Build Dynamic Feature Module
          command: ./gradlew :favorite:assembleRelease --stacktrace
          
      # Simpan semua artifacts
      - store_artifacts:
          path: app/build/reports
          destination: reports
          
      - store_artifacts:
          path: core/build/reports
          destination: core-reports
          
      - store_test_results:
          path: app/build/test-results
          
      - store_artifacts:
          path: app/build/outputs/apk/release/
          destination: release-apk

workflows:
  version: 2
  build_and_test:
    jobs:
      - build