version: 2.1
orbs:
  android: circleci/android@2.5.0
jobs:
  build:
    executor:
      name: android/android-machine
      resource-class: large
      tag: default
    steps:
      - checkout
      - run: java --version
      - restore_cache:
          key: android-orb-v1-
      - android/change-java-version:
          java-version: 17
          
      # Konfigurasi memory
      - run:
          name: Configure Gradle Memory
          command: |
            mkdir -p ~/.gradle
            echo "org.gradle.jvmargs=-Xmx6g -XX:+HeapDumpOnOutOfMemoryError" >> ~/.gradle/gradle.properties
            echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
            echo "org.gradle.parallel=true" >> ~/.gradle/gradle.properties
      
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
          
      # Disable lint untuk proses build
      - run:
          name: Disable Lint for Build
          command: |
            echo "android.lintOptions.checkReleaseBuilds=false" >> ~/.gradle/gradle.properties
            echo "android.lintOptions.abortOnError=false" >> ~/.gradle/gradle.properties
          
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
          
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
            - ~/.gradle
            
      # Build semua modul sekaligus dengan parameter untuk skip lint
      - run:
          name: Build All Modules
          command: ./gradlew assembleRelease -x lint --stacktrace
          
      # Simpan artifacts
      - store_artifacts:
          path: app/build/reports
          destination: reports
          
      - store_artifacts:
          path: core/build/reports
          destination: core-reports
          
      - store_artifacts:
          path: app/build/outputs/apk/release/
          destination: release-apk

workflows:
  version: 2
  build_and_test:
    jobs:
      - build