version: 2.1
orbs:
  android: circleci/android@2.5.0
jobs:
  build:
    executor:
      name: android/android-machine
      resource-class: large
      tag: default
    steps:
      - checkout
      - run: java --version
      - restore_cache:
          key: android-orb-v1-
      - android/change-java-version:
          java-version: 17
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      # Ubah command build untuk skip semua lint check
      - run:
          name: Run Build
          command: |
            ./gradlew assembleRelease \
            -x lint \
            -x lintVitalRelease \
            -x lintVitalAnalyzeRelease \
            --stacktrace
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_artifacts:
          path: app/build/outputs/apk/release/
          destination: release-apk

workflows:
  version: 2
  build_and_test:
    jobs:
      - build